### ISSUE TITLE
Readme says "Deprecated in lieu of Subhask", still relevant, and what were the differences you liked?

### ISSUE THREAD

**Issue by freckletonj** [leftaroundabout/constrained-categories#7]
I'm personally interested in reviving this space of a categorical prelude, and just curious what the current options are, and where I should place my efforts.

I was wondering if you could comment on this too, the Readme suggests that `subhask` will succeed `constrained-categories`? [subhask's](https://github.com/mikeizbicki/subhask/commits/master) last commit was 6 years ago and seems rather dead, and if it is indeed dead, what were some of the benefits you saw in that library over `constrained-categories`?

**Comment by leftaroundabout** [comment]
Yes good point. At the time, `subhask` looked to become more popular, so I thought it would make sense to standardise on that, but this doesn't seem to have played out. I edit the README.
